### ISSUE TITLE
Does it make sense to expand this to 256-bit instructions?

### ISSUE THREAD

**Issue by etale-cohomology** [imneme/pcg-cpp#12]
The talk on [youtube](https://www.youtube.com/watch?v=45Oet5qjlms) shows that the 64-bit version has twice the throughput of the 32-bit version (for processors that support 64-bit integers on hardware), which is pretty exciting. I wonder if PCG is suitable for extension to higher-throughput vectorized hardware instructions (ie. AVX/AVX2)?

**Comment by lemire** [comment]
Yes, it makes sense: 

https://github.com/lemire/simdpcg

**Comment by etale-cohomology** [comment]
Yay, it's the great Daniel Lemire! I've learned so much reading your blog =)

**Comment by lemire** [comment]
Thanks for the good words.
