### ISSUE TITLE
Error Uploading PCG_cpp on visual studio 2015

### ISSUE THREAD

**Issue by EliasAltrabsheh** [imneme/pcg-cpp#15]
Hello, 

I have attempted to use the pcg number generator on visual studio but constantly faced with this error in this part of code.

#ifndef PCG_LITTLE_ENDIAN
    #if defined(__BYTE_ORDER__)
        #if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
            #define PCG_LITTLE_ENDIAN 1
        #elif __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
            #define PCG_LITTLE_ENDIAN 0
        #else
            #error __BYTE_ORDER__ does not match a standard endian, pick a side
        #endif
    #elif __LITTLE_ENDIAN__ || _LITTLE_ENDIAN
        #define PCG_LITTLE_ENDIAN 1
    #elif __BIG_ENDIAN__ || _BIG_ENDIAN
        #define PCG_LITTLE_ENDIAN 0
    #elif __x86_64 || __x86_64__ || __i386 || __i386__
        #define PCG_LITTLE_ENDIAN 1
    #elif __powerpc__ || __POWERPC__ || __ppc__ || __PPC__ \
          || __m68k__ || __mc68000__
        #define PCG_LITTLE_ENDIAN 0
    #else
        #error Unable to determine target endianness  // error in this directive 
    #endif
#endif

The error is shown in this directive  comment.

**Comment by CynicalApe** [comment]
It could be because VC uses _M_X64 macro to identify x64 architecture. Could you please try adding _M_X64 macro to this line `#elif __x86_64 || x86_64 || __i386 || i386` .
It should look like `#elif __x86_64 || x86_64 || __i386 || i386 || _M_X64`

**Comment by kareldonk** [comment]
Modify that line to the below to also include 32 bit as well as 64 bit on MSVC

#elif __x86_64 || __x86_64__ || __i386 || __i386__ || _M_IX86 || _M_X64

**Comment by hero2002** [comment]
I am still getting this error on msvc 2019 and the solution works
