### ISSUE TITLE
Confusing error when trying to use a different 128 bit library

### ISSUE THREAD

**Issue by 0joshuaolson1** [imneme/pcg-cpp#18]
I rewrote the 128 bit emulation class, but the tests won't compile. What's going on here:
```
../include/pcg_uint128.hpp:48:25: fatal error: no viable conversion from 'const pcg_extras::seed_seq_from<std::random_device>' to 'uint64_t' (aka 'unsigned long')
            : UPPER(0), LOWER(rhs)
                        ^     ~~~
../include/pcg_random.hpp:1288:21: note: in instantiation of function template specialization
      'pcg_extras::uint128_t::uint128_t<pcg_extras::seed_seq_from<std::random_device> >' requested here
        : baseclass(seedSeq)
                    ^
../include/pcg_random.hpp:1296:20: note: in instantiation of function template specialization 'pcg_detail::extended<'\n', '\x80', pcg_detail::engine<unsigned long,
      pcg_extras::uint128_t, pcg_detail::xsl_rr_mixin<unsigned long, pcg_extras::uint128_t>, false, pcg_detail::oneseq_stream<pcg_extras::uint128_t>,
      pcg_detail::default_multiplier<pcg128_t> >, pcg_detail::engine<unsigned long, unsigned long, pcg_detail::rxs_m_xs_mixin<unsigned long, unsigned long>, true,
      pcg_detail::oneseq_stream<unsigned long>, pcg_detail::default_multiplier<uint64_t> >, false>::extended<pcg_extras::seed_seq_from<std::random_device>, void>'
      requested here
        new (this) extended(std::forward<Args>(args)...);
                   ^
./pcg-test-noadvance.cpp:87:13: note: in instantiation of function template specialization 'pcg_detail::extended<'\n', '\x80', pcg_detail::engine<unsigned long,
      pcg_extras::uint128_t, pcg_detail::xsl_rr_mixin<unsigned long, pcg_extras::uint128_t>, false, pcg_detail::oneseq_stream<pcg_extras::uint128_t>,
      pcg_detail::default_multiplier<pcg128_t> >, pcg_detail::engine<unsigned long, unsigned long, pcg_detail::rxs_m_xs_mixin<unsigned long, unsigned long>, true,
      pcg_detail::oneseq_stream<unsigned long>, pcg_detail::default_multiplier<uint64_t> >, false>::seed<pcg_extras::seed_seq_from<std::random_device> >' requested
      here
        rng.seed(pcg_extras::seed_seq_from<std::random_device>());
            ^
```
This is Clang++ 4.0.0. I don't understand what pcg_random.hpp:1288 is doing.

**Comment by 0joshuaolson1** [comment]
Ah, I think I get it. The new pcg_extras::uint128_t isn't templated like pcg_extras::uint_x4<typename UInt, typename UIntX2>. Why is uint_x4 parameterized? From what I saw, its implementation wouldn't work if its size was greater than 128 bits.

**Comment by 0joshuaolson1** [comment]
When the builtin __uint128_t is available, it doesn't need parameters. I'll try adding dummy templates all over the place, but do they need to be there in your code?

**Comment by imneme** [comment]
The code you queried is template metaprogramming. We're essentially constraining the parameter of this constructor (which is designed to receive any kind of seed sequence), saying it what it can't be so that we can match anything except types for which there is a preexisting more-specialized constructor.  Specifically, `std::is_convertible<SeedSeq, extended>::value>::type>` is saying the argument to this can't be something that ought to be going to the copy constructor, and `std::is_convertible<SeedSeq, result_type>::value` is saying things that could go to the constructor that takes a `result_type`.

My guess is that your class doesn't support some necessary type conversion, so the `is_convertible`-to-`result_type` test fails for some argument.

**Comment by imneme** [comment]
> Why is uint_x4 parameterized? From what I saw, its implementation wouldn't work if its size was greater than 128 bits.

I believe you are mistaken. As I recall, it'll happily do any power-of-two size of bits.

> I'll try adding dummy templates all over the place, but do they need to be there in your code?

I don't understand why you're doing what you're doing. It seems like you're trying to rewrite code you don't really understand.

**Comment by 0joshuaolson1** [comment]
My bad. What I'm trying to do to use a different 128-bit library. Does what I choose have to work for larger sizes too?

**Comment by imneme** [comment]
No. You can use any type that “feels like an unsigned int”, you shouldn't have to look at the existing library much, other than to see what operations I do/don't support.

**Comment by 0joshuaolson1** [comment]
Thanks. So I'm probably missing some copy constructor?

**Comment by imneme** [comment]
Seems plausible.  Since only you can see your code, only you'll know for sure.

**Comment by 0joshuaolson1** [comment]
And by 'dummy templates' I meant in my library, not modifying your code.

**Comment by imneme** [comment]
If it just supports one size, I don't see why it would need to be a template at all. The builtin types `uint8_t`, `uint16_t`, `uint32_t` and `uint64_t` aren't templates.

**Comment by 0joshuaolson1** [comment]
If I may ask a related off-topic question, why did pcg_uint128 end up being generic? For fun?
