### ISSUE TITLE
are pcg distributions reproducible

### ISSUE THREAD

**Issue by pwm1234** [imneme/pcg-cpp#22]
I recently struggled getting the new C++11 random number distributions to work in my algorithm only to find that the distributions generate different sequences when run on different platforms (VS 2015 on windows gcc 5 on ubuntu 16). In my googling for an alternative, I came across PCG, which looks promising. Specifically, I am using ```std::uniform_int_distribution<unsigned int>``` with a fixed seed for ```std::mt19937 ```. Will using PCG give me a reproducible sequence across ALL (most or even some) implementations?

Thanks,
Phil

**Comment by imneme** [comment]
The distribution objects in C++ are not required to behave the same across different platforms.

In contrast, PCG does provide a way to get an integer in a range, see the docs [here](http://www.pcg-random.org/using-pcg-cpp.html#result-type-pcg32-operator-result-type-upper-bound).
