### ISSUE TITLE
Pointer Truncation warnings when using MSVC

### ISSUE THREAD

**Issue by kareldonk** [imneme/pcg-cpp#34]
When using the _unique versions of  pcg_random I get warnings when compiling with MSVC (Visual Studio 2017):

>pcg_random.hpp(206): warning C4302: 'reinterpret_cast': truncation from 'const pcg_detail::unique_stream<itype> *' to 'unsigned long'

> pcg_random.hpp(206): warning C4311: 'reinterpret_cast': pointer truncation from 'const pcg_detail::unique_stream<itype> *' to 'unsigned long'

The issue is on line 206 in pcg_random.hpp: 

`return itype(reinterpret_cast<unsigned long>(this) | 1);`

Pointer truncation is probably no issue seeing as how it's used in pcg_random, so to turn off the warnings I'm disabling the warnings before including the pcg_random header:

```
#pragma warning(push)
#pragma warning(disable:4302)
#pragma warning(disable:4311)
#include <pcg_random.hpp>
#pragma warning(pop)
```

Perhaps a fix in your header would be better for the future.

**Comment by lemire** [comment]
Spurious warnings should be turned off, but it seems ugly to do it in the source code itself and I would find it particularly ugly to do so within a library such as this one. What you are doing is probably fine for your own purposes... but I don't think it should be generalized.

Note that Visual Studio is very eager to throw warnings after warnings, most of them being false positives. It is a defect in the compiler itself. So you can simply pass ``/wd4302 /wd4311`` and be done with it.  There is simply no evidence that chasing these warnings makes for better code.

Compiler warnings are an important feature, but it only makes sense if the rate of false positives is low. Microsoft is flat out misguided in this instance.

**Comment by kareldonk** [comment]
These warnings are actually very useful and a pointer truncation is a serious problem you'd want to detect. I would have hoped GCC and Clang would also warn about it. However in this case it's not an issue seeing as how the value is just being used as an initial seed and not as a pointer. In any case it's up to the library author what they want to do in this case. I think it may not be nice for new users to get these warnings when they compile their code and don't know what's going on.

**Comment by lemire** [comment]
>  I would have hoped GCC and Clang would also warn about it. 

The standard allows you to cast a pointer to any integral type that can hold it. If you try a cast to an integral type that cannot hold a pointer, both clang and gcc will correctly throw an error (not a warning). So will the Intel compiler.

*If* you are using 64-bit pointers (``sizeof(long *) == 8``) and unsigned longs are too small (``sizeof(unsigned long) < 8``), then there is an issue that needs fixing.

Most compilers, except maybe visual studio, have sizeof(long) defined to be the machine word size. So ``reinterpret_cast<unsigned long>(&a)`` is fine under these compilers. It is likely fine also under Visual Studio if you are compiling in 32-bit mode. If you are using the compiler in 64-bit mode, and this code comes up (``reinterpret_cast<unsigned long>(&a)``) then it is wrong.

**Comment by imneme** [comment]
Probably the code should cast to `uintptr_t` rather than unsigned long, I was clearly being a bit old school.

**Comment by kareldonk** [comment]
@lemire in 64-bit you'd have to cast to `unsigned long long`.

@imneme I can confirm that casting to `uintptr_t` removes the warnings when compiling in 64-bit and 32-bit.

**Comment by imneme** [comment]
Fixed.
