### ISSUE TITLE
Why xoshiro256** is better

### ISSUE THREAD

**Issue by PiotrGrochowski** [imneme/pcg-cpp#57]
• Vigna recommends converting from a 64-bit seed to a 256-bit state with SplitMix64
• Runs fast on 32-bit and 64-bit `x86` architectures
• Public domain
• Vigna recommends using a 64-bit mod operation to reduce to range
• Linearity (not even a problem in most cases in the first place) filtered out entirely with **
• Periodic 2^256-1 (did I mention this works on 32-bit as well)
• Not a hacked version of LCG but proven to have certain properties
• Not a slow full state multiply invented entirely by M.O'Neill

**Comment by imneme** [comment]
Thanks for your thoughts!

I haven't closely examined Vigna's most recent work, but on cursory examination it also appears not to be trivially predictable, which is a plus in my book. If you like it, use it. [You don't have to use PCG.](http://www.pcg-random.org/posts/other-good-options.html)

**Comment by PiotrGrochowski** [comment]
Uh what? Why would you avoid trivial predictability... .... .if the random number generators are not cryptographically secure?

**Comment by PiotrGrochowski** [comment]
"(Sadly, Xoroshiro128+ and Xorshift128+ are not on this list. I thought they were good because good claims are made about them, but I have recently discovered otherwise. You can test them yourself with PractRand or TestU01 and determine their quality; it's quite easy to do. You can also read the caveats given in their source code. Or you can wait: a blog post is coming. The news isn't good.)"

xoroshiro128+ is the successor of xorshift128+. The hammingweight issues are not a problem in most cases, and to avoid that you could instead use xoroshiro128**, or xoshiro256+.

**Comment by imneme** [comment]
For predictability, read [On Trivial Predictability](http://www.pcg-random.org/posts/on-trivial-predictability.html).

As for your quote from the other 2017 blog post, don't be surprised that it doesn't talk about work done after 2017.

Even if you don't see it this way, Vigna and I do similar things.  We both take an old technique (LFSRs for him, LCGs for me), and add a scrambling output function to it.  Over time, Vigna has improved both his underlying LFSR and his output function.

It seems pretty clear that you came here to troll. Please find a better way to spend your time.
