### ISSUE TITLE
Have you considered designing a PCG without the constraint that it has to be "challenging" to predict?

### ISSUE THREAD

**Issue by nsajko** [imneme/pcg-cpp#65]
Firstly, you should know that I am not "trolling" you, and that I'm writing this because I appreciate your work designing PRNGs (and a lot of your blog posts and similar have been valuable and enjoyable to me). I understand that trivial [predictability](https://www.pcg-random.org/predictability.html) seems to be your [pet](https://www.pcg-random.org/posts/on-trivial-predictability.html) peeve. However, as far as I understand, "challenging" predictability comes at some cost for either statistical quality or speed, and you yourself acknowledge that 

> Algorithmic-complexity attacks aren't a major risk for our algorithms most of the time

So why not give users who don't need "challenging" predictability the option of using a PRNG that is tailored purely for excellent statistical quality, speed and small state size?

Furthermore, and I hope that writing this is a good idea, but I believe that your reasoning for making "challenging" predictability a goal at all is flawed, and your claims regarding the predictability of PCGs are deceptive.

The problem is that if someone needs to worry about algorithmic complexity attacks, PCG is not the right choice for them anyway, rather something like [Randen](https://github.com/google/randen) seems to be a proper choice. The reason is that, as you yourself acknowledge, the PCG family is not cryptographically strong, i.e. the "challenging" predictability can not be relied on. In other words, _trivial_ vs _challenging_ predictability isn't a useful distinction. I'm pretty sure you already know that, unsurprisingly, a relatively efficient attack has already been [described](https://hal.inria.fr/hal-02700791/). Another thing that should be noted is that in your reasoning about the threat model you suppose that an attacker may only choose the easiest target; while in the real world determined and resourceful attackers with specific targets do exist. Such an attacker may even, for example, implement custom hardware to help with efficiently breaking the PRNG at hand.

To reiterate my point, one either worries about attacks on the PRNG, in which case they can use Randen or a CSPRNG; or they don't and they need good statistical quality and probably also speed, in which case they may use a PCG.

I hope you can appreciate my honesty, are not offended and your desire for making a trivially predictable PCG increases.

**Comment by imneme** [comment]
Thanks for your thoughts.

There are already PCG variants that are not challenging to predict. The `_once` variants, for example.

For me though, a PRNG that is trivial to predict doesn't “feel” very random.
