### ISSUE TITLE
pcg32_k2 is incorrectly defined

### ISSUE THREAD

**Issue by nixprime** [imneme/pcg-cpp#9]
Both pcg32_k2 and pcg32_k2_fast are defined with template parameter table_log2 = 6, making them 64-dimensionally equidistributed and requiring substantially more storage than the expected 2-dimensionally equidistributed generators. This is particularly obvious if we note that pcg32_k2 and pcg32_k64 have the same definition, as do pcg32_k2_fast and pcg32_k64_fast.

I'm submitting an issue rather than a PR because I'm not sure how advance_pow2 is chosen.

**Comment by 0joshuaolson1** [comment]
This can be closed.

**Comment by imneme** [comment]
Thanks!
